data = [
(1,"Time","Thời Gian"),
(2,"Year","Năm"),
(3,"People","Mọi Người"),
(4,"Way","Đường"),
(5,"Day","Ngày"),
(6,"Man","Đàn Ông"),
(7,"Thing","Điều"),
(8,"Woman","Đàn Bà"),
(9,"Life","Đời Sống"),
(10,"Child","Đứa Trẻ"),
(11,"World","Thế Giới"),
(12,"School","Trường Học"),
(13,"State","Tiểu Bang"),
(14,"Family","Gia Đình"),
(15,"Student","Sinh Viên"),
(16,"Group","Nhóm"),
(17,"Country","Quốc Gia"),
(18,"Problem","Vấn Đề"),
(19,"Hand","Tay"),
(20,"Part","Phần"),
(21,"Place","Địa Điểm"),
(22,"Case","Trường Hợp"),
(23,"Week","Tuần"),
(24,"Company","Công Ty"),
(25,"System","Hệ Thống"),
(26,"Program","Chương Trình"),
(27,"Question","Câu Hỏi"),
(28,"Work","Công Việc"),
(29,"Government","Chính Quyền"),
(30,"Number","Con Số"),
(31,"Night","Đêm"),
(32,"Point","Điểm"),
(33,"Home","Nhà"),
(34,"Water","Nước"),
(35,"Room","Phòng"),
(36,"Mother","Mẹ"),
(37,"Area","Khu Vực"),
(38,"Money","Tiền Bạc"),
(39,"Story","Câu Chuyện"),
(40,"Fact","Sự Thật"),
(41,"Month","Tháng"),
(42,"Lot","Nhiều"),
(43,"Right","Đúng"),
(44,"Study","Học"),
(45,"Book","Sách"),
(46,"Eye","Mắt"),
(47,"Job","Việc Làm"),
(48,"Word","Từ"),
(49,"Business","Kinh Doanh"),
(50,"Issue","Vấn Đề"),
]
